services:
  signstream:
    image: node:latest
    working_dir: /signstream
    volumes:
      - .:/signstream
    ports:
      - "3000:3000"
    env_file:
      - .env
    depends_on:
      - mongo
    command: sh -c "npm i && npm start"

  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
