services:
  signstream:
    image: node:18
    working_dir: /signstream
    volumes:
      - .:/signstream
    ports:
      - "3000:3000"
    environment:
      CLOUDINARY_API_SECRET: ${CLOUDINARY_API_SECRET}
      CLOUDINARY_API_KEY: ${CLOUDINARY_API_KEY}
      CLOUDINARY_CLOUD_NAME: ${CLOUDINARY_CLOUD_NAME}
      JWT_SECRET: ${JWT_SECRET}
      MONGODB_STRING : ${MONGODB_STRING}
    depends_on:
      - mongo
    command: sh -c "npm i && node server.js"
    restart: always

  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
